modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="Tangwenjun"
logoFile ="${mod_id}.png"
description='''
为龙之生存添加桶滚飞行机制——俯仰、偏航、滚转，像战斗机一样自由飞翔。
Adds barrel roll flight mechanics to Dragon Survival — pitch, yaw, and roll freely like a fighter jet.
'''
[[mixins]]
    config="${mod_id}.mixins.json"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="dragonsurvival"
    type="required"
    versionRange="[2.0.45,)"
    mandatory=true
    ordering="BEFORE"
    side="BOTH"

# Start of user code block dependencies configuration
# End of user code block dependencies configuration